version: '2.1'
orbs:
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  delete:
    docker:
      - image: cimg/base:stable
    steps:
      - kubernetes/install-kubectl
      - kubernetes/delete-resource:
          now: true
          resource-names: nginx-deployment
          resource-types: deployments
          wait: true
workflows: null

