# orb.yml
version: 2.1

orbs:
  my-orb:
    description: "A simple orb"
    commands:
      my-command:
        description: "My command"
        parameters:
          my-param:
            type: string
            default: "default_value"
        steps:
          - run: echo "My command was executed with param: ${{ orb.parameters.my-param }}"

workflows:
  my-workflow:
    jobs:
      - my-job

jobs:
  my-job:
    executor: my-orb/default
    steps:
      - my-orb/my-command:
          my-param: "custom_value"





