version: 2.1
jobs:
  ahtesham-job:
    resource_class: ahteshamahmad/rhl_system_runner
    machine:
      image: ubuntu-2004:202201-01
    steps:
      - run: echo "Hello Md Ahtesham"
workflows:
  my-workflow:
    jobs:
      - ahtesham-job

