version: 2.1

orbs:
  node: circleci/kubernetes@1.3.1

jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - kubernetes/install-kubectl
      - kubernetes/delete-resource:
          now: true
          resource-names: nginx-deployment
          resource-types: deployments
          wait: true
workflows:
  test_my_app:
    jobs:
      - install-node-example


