version: 2.1

orbs:
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubectl
workflows:
  test_my_app:
    jobs:
      - install-node-example


